<?xml version="1.0" encoding="utf-8"?><Database Name="FlowerDB" Class="FlowerDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-BD2VFN78\SQLSERVER;Initial Catalog=FlowerDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FlowerDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Flower_table" Member="Flower_tables">
    <Type Name="Flower_table">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FlowerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>